/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://oto7r44cyjgefjok7qndgqlh5m.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2ew6ranjmfc4xcoqqobxvpcmuq",
    "aws_cognito_identity_pool_id": "us-west-2:d35704b0-9c09-4453-8f05-193f7a49f470",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_WSThFIdZh",
    "aws_user_pools_web_client_id": "4bkkmmacd10ogdikk2bbg7psu5",
    "oauth": {}
};


export default awsmobile;
